### ISSUE TITLE
Contribute to the Maven GPG Plugin

### ISSUE THREAD

**Issue by brunoborges** [s4u/pgpverify-maven-plugin#242]
Hey friends,

Was there any conversation about moving/merging contributing this functionality to the core Maven GPG plugin?

http://maven.apache.org/plugins/maven-gpg-plugin/

**Comment by slawekjaranowski** [comment]
`maven-gpg-plugin` has different responsibility - it should generate signature. 

Verification of signature should be done in maven core, there are related issues in maven jira:
https://issues.apache.org/jira/browse/MNG-5814
https://issues.apache.org/jira/browse/MNG-6026

as we see those issues has about 5 year old

**Comment by mkarg** [comment]
Bruno, we did our work *here* because, besides more reasons, at Apache nobody seemed to be overly eager to adopt our changes. If this has changes, we all would be happy to contribute. As a first step, there should be a concensus at the maven-gpg-team that they want to replace original GPG by our code. It makes no sense to do anything before that.

**Comment by brunoborges** [comment]
Thanks all for bringing more context into this! This was super helpful! I'll chat with couple other folks in the Maven team.

**Comment by slawekjaranowski** [comment]
Now I close it ... 
If you will have some new information don't hesitate reopen
I  cooperate with Apache Maven team so I'm up to date.
