### ISSUE TITLE
Builds with "noKey" fail when any keyserver is down

### ISSUE THREAD

**Issue by aoindustries** [s4u/pgpverify-maven-plugin#305]
PR https://github.com/s4u/pgp-keys-map/pull/229 build was failing while pgp.mit.edu was down.  pgp.mit.edu has a history of going down, and while down builds relying on "noKey" will fail.

I suggest that "noKey" map entries not even attempt to query any keyservers.  This would avoid the overhead of querying every keyserver on every build, and also will not fail builds when any of the keyservers are down.

I tried various combinations of "*", "noSig", "badSig", and "noKey" and was unable to find a way to prevent the keyserver lookup.

Related, other projects have avoiding using pgp.mit.edu, as it is a single server.  Instead, they only use keyserver pools: https://github.com/nginxinc/docker-nginx/issues/156

**Comment by slawekjaranowski** [comment]
sks-keyservers.net is down ... #296

**Comment by slawekjaranowski** [comment]
My proposition is to store 404 status in cache. 
When we first lookup for key and will be not available we store such information and next lookup will not occurs but identical exception should be thrown by cache like during real key download.

Because key can appears in some time we should invalidate such information for time to time. Invalidation should be implemented in #284

**Comment by slawekjaranowski** [comment]
will be continued in another issue.
