### ISSUE TITLE
Store `key not found` in cache

### ISSUE THREAD

**Issue by slawekjaranowski** [s4u/pgpverify-maven-plugin#313]
When key is not published to public key servers we don't need look up for key every time verification is run.

We can store this information in cache and (re-try after cache invalidated).

Continuation for: #305 

May impact on: #284

**Comment by protocol7** [comment]
Just checking in on the progress on this feature. We're looking at using pgpverify-maven-plugin for a project with a very large number of dependencies, and since this contains a number of dependencies without keys, this is currently slowing down the build quite significantly.

My experience with Maven plugins is limited, so not sure to what extent I would be able to help with a patch. But if there's anything I can do to support, I'm happy to do so.

**Comment by slawekjaranowski** [comment]
Thanks for interesting .... I will try to fix it ... Anyway any help in this is appreciated

**Comment by protocol7** [comment]
I can certainly offer to review any PR and try it out on our use case.

**Comment by slawekjaranowski** [comment]
@protocol7 - PR ready - waiting for your review

**Comment by protocol7** [comment]
Thanks, tested. Found a bug which I've made a suggestion to fix in the PR, but with that fix in place it works as expected for our case.
