### ISSUE TITLE
Question: Source of truth?

### ISSUE THREAD

**Issue by stevespringett** [s4u/pgpverify-maven-plugin#55]
I just discovered this plugin. Seems to be very useful. Thank you.

Question. If using an internal Nexus repo, then I execute this plugin will the internal repo be the source of truth for signature verifications or will the repo of origin (e.g. Maven Central) be the source of truth?

Errors during mirroring occur, as does the possibility of accidental or malicious modification to internal repos. I'd like the ability to use the repo of origin (typically Maven Central for OSS components and internal Nexus for internally developed components) when validating signatures.

Is that the way this plugin works, and if not, is there any way to achieve what I'm after?

**Comment by cobratbq** [comment]
Signature files are resolved through Maven's own mechanism ([maven-resolver-plugin](https://maven.apache.org/resolver/)), IIRC, so it should respect both proxy settings and mirroring settings. So that's your primary source of signatures. I think it might be more likely that _pgpverify_ will fail to find the signature for a package, rather than fallback to the internet sources. Or it may depend on how your local mirror is configured.

If I understand you correctly, regarding your underlying problem ... you want to ensure that the results are trustworthy, correct?
1. Using a keys map (either from the [pgp-keys-map](https://github.com/s4u/pgp-keys-map) repo or your own composition) will explain to pgpverify to not trust any valid signature, but rather one specific public key.
2. Then, whether you download a signature from your internal mirror or an "authentic" internet service, it does not really matter. Because: if validation fails, then it's either a corrupted dependency/plugin artifact, or it is something bad in the signature. The badness in the signature can be validated against the keys map. The badness in the artifact would invalidate the signature, so in any case you're alerted.

You might want to verify your keys map from outside, say a company network, if you want to make sure that you acquire the same results inside and outside.

Did I manage to capture all of your concerns?

**Comment by slawekjaranowski** [comment]
It doesn't matter how you download artifact. You can download they directly from internet, by proxy or by internal repository manager.

Only author of artifact has private key and only author has possibility to create correct signature.

So using this plugin connected with static map key fingerprint to artifacts you have sure that used artifact was not changed by any one.

As @cobratbq  said you can use publicly accessible map which was verified by other users.

One another benefit of using this plugin is that artifact is checked during each build, not only during download, so you have sure that your local copy of artifacts is also correct.

**Comment by stevespringett** [comment]
Thanks a lot for the clarifications. Yes, trustworthyness is the property that I'm after. So the map seems like the way to help me achieve that.

Thanks again. Looking forward to using the plugin in my work and personal projects.
